CP = 3985.       #: specific heat capacity of seawater
RHO0 = 1025.
GRAVITY = 9.81   #: gravitational acceleration

CENTERS = 1
INTERFACES = 2

ZERO_GRADIENT = 1
SOMMERFELD = 2
CLAMPED = 3
FLATHER_ELEV = 4
SPONGE = 5

FILL_VALUE = -2e20

BAROTROPIC = BAROTROPIC_2D = 1
BAROTROPIC_3D = 2
FROZEN_DENSITY = 3
BAROCLINIC = 4
